CREATE DATABASE futebolnet;

USE futebolnet;

CREATE TABLE devices (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
ip_address VARCHAR(50) NOT NULL,
type VARCHAR(50),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE tests(
id INT AUTO_INCREMENT PRIMARY KEY,
device_id INT NOT NULL,
status VARCHAR(20) NOT NULL,
latency DECIMAL(10, 2),
timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(device_id) REFERENCES devices(id) ON DELETE CASCADE
);

select * from devices;